### ISSUE TITLE
Webpack 5 Support Plan?

### ISSUE THREAD

**Issue by septs** [jantimon/html-webpack-plugin#1269]
The webpack 5.0 changelog
https://github.com/webpack/changelog-v5/blob/master/README.md

@jantimon

**Comment by jantimon** [comment]
It is not possible to support webpack 4 and webpack 5 with one version

Therefore I would like to release html-webpack-plugin 4 first before deprecating it 😄

**Comment by septs** [comment]
@jantimon Will the next version migrate to TypeScript?

**Comment by jantimon** [comment]
We are already using typescript salsa https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc

**Comment by septs** [comment]
I hope to expose the definition of `getHooks` in `typings.d.ts`.
I am developing a plugin based on `html-webpack-plugin`.

**Comment by septs** [comment]
@jantimon

**Comment by jantimon** [comment]
If you enable allowJs in your tsconfig it should work :)

**Comment by septs** [comment]
Pure TypeScript Project, Enable strict-mode.

**Comment by jantimon** [comment]
That should work fine

**Comment by hanzenok** [comment]
@jantimon Dont know if it is a good place to ask but are there any dates on new release?

Testing the **4.0.0-beta.8** and it's quite a performance booster!

**Comment by septs** [comment]
@jantimon webpack 5 release, first beta version.
https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.0

**Comment by rwieruch** [comment]
Initially 4.0.0-beta.8 works with Webpack 5.0.0-beta.0. https://github.com/rwieruch/advanced-react-webpack-babel-setup/commit/d2e6d58cbf31cc7db09decad79f7dc0c22a287c6

But once I change source code, I run into https://github.com/webpack/webpack/issues/9802#issuecomment-542647047:

```
/Users/mydspr/Developer/Repos/advanced-react-webpack-babel-setup/node_modules/html-webpack-plugin/lib/compiler.js:341
    const timestamp = fileTimestamps.get(fileDependency);
                                     ^

TypeError: Cannot read property 'get' of undefined
    at childCompiler.fileDependencies.some (/Users/mydspr/Developer/Repos/advanced-react-webpack-babel-setup/node_modules/html-webpack-plugin/lib/compiler.js:341:38)
    at Array.some (<anonymous>)
    at isChildCompilerCacheOutdated (/Users/mydspr/Developer/Repos/advanced-react-webpack-babel-setup/node_modules/html-webpack-plugin/lib/compiler.js:340:59)
    at Object.hasOutDatedTemplateCache (/Users/mydspr/Developer/Repos/advanced-react-webpack-babel-setup/node_modules/html-webpack-plugin/lib/compiler.js:321:16)
    at compiler.hooks.thisCompilation.tap (/Users/mydspr/Developer/Repos/advanced-react-webpack-babel-setup/node_modules/html-webpack-plugin/index.js:135:25)
    at Hook.eval [as call] (eval at create (/Users/mydspr/Developer/Repos/advanced-react-webpack-babel-setup/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Compiler.newCompilation (/Users/mydspr/Developer/Repos/advanced-react-webpack-babel-setup/node_modules/webpack/lib/Compiler.js:713:30)
    at hooks.beforeCompile.callAsync.err (/Users/mydspr/Developer/Repos/advanced-react-webpack-babel-setup/node_modules/webpack/lib/Compiler.js:754:29)
    at Hook.eval [as callAsync] (eval at create (/Users/mydspr/Developer/Repos/advanced-react-webpack-babel-setup/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Compiler.compile (/Users/mydspr/Developer/Repos/advanced-react-webpack-babel-setup/node_modules/webpack/lib/Compiler.js:749:28)
```

**Comment by kirill-konshin** [comment]
Somehow HTML plugin is causing this error:

```
ERROR in   TypeError: Cannot read property 'tap' of undefined
  
  - ExternalModuleFactoryPlugin.js:17 ExternalModuleFactoryPlugin.apply
    [web-modules-core]/[webpack]/lib/ExternalModuleFactoryPlugin.js:17:37
  
  - ExternalsPlugin.js:16 
    [web-modules-core]/[webpack]/lib/ExternalsPlugin.js:16:63
  
  
  - Hook.js:14 Hook.CALL_DELEGATE [as _call]
    [build]/[tapable]/lib/Hook.js:14:14
  
  - Compiler.js:890 
    [build]/[webpack]/lib/Compiler.js:890:23
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [build]/[tapable]/lib/Hook.js:18:14
  
  - Compiler.js:887 Compiler.compile
    [build]/[webpack]/lib/Compiler.js:887:28
  
  - Compiler.js:432 Compiler.runAsChild
    [build]/[webpack]/lib/Compiler.js:432:8
  
  - compiler.js:129 
    [web-modules-core]/[html-webpack-plugin]/lib/compiler.js:129:21
```

When I remove HTML plugin from config everything works.

**Comment by jantimon** [comment]
The problem is this bug: #1129

**Comment by kirill-konshin** [comment]
Seems that it's working now, version `4.2.0`?

**Comment by jantimon** [comment]
Yes `4.2.0` supports webpack 5
