### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by Realybig** [jantimon/html-webpack-plugin#1428]
**Why did this error appear when I modified the page, the page did not refresh**

config
``` js
webpack4
"webpack-hot-middleware": "^2.12.2"

// dev-server.js
var hotMiddleware = require('webpack-hot-middleware')(compiler, {
    log: () => {}
});
// force page reload when html-webpack-plugin template changes
compiler.plugin('compilation', function (compilation) {
    compilation.plugin('html-webpack-plugin-after-emit', function (data, cb) {
        console.log('html-webpack-plugin-after-emit', data, cb)
        hotMiddleware.publish({ action: 'reload' });
        cb();
    });
});
```

``` js
TypeError: cb is not a function
    at /Users/labs/webpack/office/build/dev-server.js:39:9
    at Promise (eval at create (/Users/labs/webpack/office/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:17:16)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (/Users/labs/webpack/office/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:4:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/labs/webpack/office/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/labs/webpack/office/node_modules/html-webpack-plugin/index.js:673:47
    at Promise.resolve.then.then.then.then.then.then.then.then.catch.then.then (/Users/labs/webpack/office/node_modules/html-webpack-plugin/index.js:214:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jantimon** [comment]
Which version are you using?

**Comment by Realybig** [comment]
> Which version are you using?

"html-webpack-plugin": "^3.2.0"

**Comment by jantimon** [comment]
3.2.0 is 2 years old can you try to upgrade to 4.x and use the new event system?

https://github.com/jantimon/html-webpack-plugin#events

**Comment by Realybig** [comment]
thank you so much，maybe i know what to do。：）

**Comment by amourfrei** [comment]
try this:
```
        if (callback) {
          return callback(null, data);
        } else {
          return Promise.resolve(data);
        }
```
