### ISSUE TITLE
Generating Multiple HTML Files

### ISSUE THREAD

**Issue by EgoPingvina** [jantimon/html-webpack-plugin#1447]
I have this entry/output:

        entry:
            {
                content: './js/content.js',
                background: './js/background.js',
                popup: './js/popup.js',
                view: './js/view.js'
            },

        output:
            {
                path: __dirname + '/build',
                filename: 'js/[name].js'
            },

I hav had one HTML for popup already. And in `popus.js` I want to create chrome tab like this:

                chrome.tabs.create(
                    {
                        url: chrome.extension.getURL('view.html'),
                        'index': tabs[0].index + 1
                    })));

And for it, if I not mistake, I should use `html-webpack-plugin` twice:

                new HtmlWebpackPlugin(
                    {
                        filename: 'popup.html',
                        template: './popup.html',
                        chunks: [ 'popup' ]
                    }),
                new HtmlWebpackPlugin(
                    {
                        filename: 'view.html',
                        template: './view.html',
                        chunks: [ 'view' ]
                    }),

But it doesn't work. From log:

    13 verbose stack Exit status 2
    13 verbose stack     at EventEmitter.<anonymous> (D:\Programs\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
    13 verbose stack     at EventEmitter.emit (events.js:310:20)
    13 verbose stack     at ChildProcess.<anonymous>(D:\Programs\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
    13 verbose stack     at ChildProcess.emit (events.js:310:20)
    13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

And this problem fires when I add second HtmlWebpackPlugin. Bit I see in read.me that it is normal. Why it doesn't work for me?

**Comment by EgoPingvina** [comment]
Sorry, I found my mistake in naming, all works well.
