### ISSUE TITLE
html-webpack-plugin breaking when I pass template

### ISSUE THREAD

**Issue by saurabh-sharma** [jantimon/html-webpack-plugin#1482]
I am using the config like this:
```js
        new HtmlWebpackPlugin({
            template: './src/index.html',
            cache: false,
            minify: {
                removeComments: true,
                collapseWhitespace: true,
                conservativeCollapse: true
            },
            showErrors: true,
        }),
```

and I am getting the following error:

```
ERROR in   Error: Child compilation failed:
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  TypeError: Cannot read property 'code' of undefined
  
  - index.js:67 parser
    [react-boilerplate]/[@babel]/core/lib/parser/index.js:67:13
  
  - parser.next
  
  - normalize-file.js:93 normalizeFile
    [react-boilerplate]/[@babel]/core/lib/transformation/normalize-file.js:93:38
  
  - normalizeFile.next
  
  - index.js:31 run
    [react-boilerplate]/[@babel]/core/lib/transformation/index.js:31:50
  
  - run.next
  
  - transform.js:27 Function.transform
    [react-boilerplate]/[@babel]/core/lib/transform.js:27:41
  
  - transform.next
  
  - index.js:254 step
    [react-boilerplate]/[gensync]/index.js:254:32
  
  - index.js:266 
    [react-boilerplate]/[gensync]/index.js:266:13
  
  
  - TypeError: Cannot read property 'code' of undefined
  
  - child-compiler.js:122 
    [react-boilerplate]/[html-webpack-plugin]/lib/child-compiler.js:122:18
  
  - Compiler.js:343 
    [react-boilerplate]/[webpack]/lib/Compiler.js:343:11
  
  - Compiler.js:681 
    [react-boilerplate]/[webpack]/lib/Compiler.js:681:15
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [react-boilerplate]/[tapable]/lib/Hook.js:154:20
  
  - Compiler.js:678 
    [react-boilerplate]/[webpack]/lib/Compiler.js:678:31
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [react-boilerplate]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1423 
    [react-boilerplate]/[webpack]/lib/Compilation.js:1423:35
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [react-boilerplate]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1414 
    [react-boilerplate]/[webpack]/lib/Compilation.js:1414:32
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [react-boilerplate]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1409 
    [react-boilerplate]/[webpack]/lib/Compilation.js:1409:36
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [react-boilerplate]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1405 
    [react-boilerplate]/[webpack]/lib/Compilation.js:1405:32
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [react-boilerplate]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1342 Compilation.seal
    [react-boilerplate]/[webpack]/lib/Compilation.js:1342:27
  
  - Compiler.js:675 
    [react-boilerplate]/[webpack]/lib/Compiler.js:675:18
  
  - Compilation.js:1261 
    [react-boilerplate]/[webpack]/lib/Compilation.js:1261:4
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [react-boilerplate]/[tapable]/lib/Hook.js:154:20
  
  - Compilation.js:1253 Compilation.finish
    [react-boilerplate]/[webpack]/lib/Compilation.js:1253:28
  
  - Compiler.js:672 
    [react-boilerplate]/[webpack]/lib/Compiler.js:672:17
  
  
  - Compilation.js:1185 
    [react-boilerplate]/[webpack]/lib/Compilation.js:1185:12
  
  - Compilation.js:1097 
    [react-boilerplate]/[webpack]/lib/Compilation.js:1097:9
  
  - task_queues.js:79 processTicksAndRejections
    internal/process/task_queues.js:79:11




ERROR in ./src/index.html (./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html)
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: Cannot read property 'code' of undefined
        at parser (/Users/ss/Projects/react-boilerplate/node_modules/@babel/core/lib/parser/index.js:68:13)
        at parser.next (<anonymous>)
        at normalizeFile (/Users/ss/Projects/react-boilerplate/node_modules/@babel/core/lib/transformation/normalize-file.js:93:38)
        at normalizeFile.next (<anonymous>)
        at run (/Users/ss/Projects/react-boilerplate/node_modules/@babel/core/lib/transformation/index.js:31:50)
        at run.next (<anonymous>)
        at Function.transform (/Users/ss/Projects/react-boilerplate/node_modules/@babel/core/lib/transform.js:27:41)
        at transform.next (<anonymous>)
        at step (/Users/ss/Projects/react-boilerplate/node_modules/gensync/index.js:254:32)
        at /Users/ss/Projects/react-boilerplate/node_modules/gensync/index.js:266:13
        at async.call.result.err.err (/Users/ss/Projects/react-boilerplate/node_modules/gensync/index.js:216:11)
        at /Users/ss/Projects/react-boilerplate/node_modules/gensync/index.js:184:28
        at /Users/ss/Projects/react-boilerplate/node_modules/@babel/core/lib/gensync-utils/async.js:72:7
        at /Users/ss/Projects/react-boilerplate/node_modules/gensync/index.js:108:33
        at step (/Users/ss/Projects/react-boilerplate/node_modules/gensync/index.js:280:14)
        at /Users/ss/Projects/react-boilerplate/node_modules/gensync/index.js:266:13
        at async.call.result.err.err (/Users/ss/Projects/react-boilerplate/node_modules/gensync/index.js:216:11)
```

```
Node.js v14.4.0
darwin 19.5.0
webpack@4.43.0 
html-webpack-plugin@4.3.0 
```

### Config

```js
module.exports = {
   entry: ["@babel/polyfill", "./src/index.js"],
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist'),
        publicPath: '/'
    },
  module: {
    rules: [
      ...
    ]
  }
  plugins: [
    new HtmlWebpackPlugin({
            template: './src/index.html',
            cache: false,
            minify: {
                removeComments: true,
                collapseWhitespace: true,
                conservativeCollapse: true
            },
            showErrors: true,
        }),
    ...
  ]
}
```

Copy your template file if it is part of this issue:

```html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>React App</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <!--[if lt IE 10]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div id="app"></div>
        
    </body>
</html>
```

If I remove template, It works just fine but uses its default html template
If I pass a template it breaks with the error listed above. still unable to figure out what's going on with it

**Comment by saurabh-sharma** [comment]
Somehow the pattern for `/.(jsx|js)?$/` was not working if I used html-webpack-plugin. Changed the pattern to `/\.jsx?$/` and it started working.

```js
module.exports = {
...
  module: {
    rules: [
            {
                test: /\.jsx?$/,
                exclude: [
                    path.resolve(__dirname, 'node_modules'),
                ],
  }
```
