### ISSUE TITLE
html-webpack-plugin with webpack has error

### ISSUE THREAD

**Issue by zeyueZhang** [jantimon/html-webpack-plugin#1496]
### **Environment**

webpack@4.44.1
html-webpack-plugin@4.3.0

```
Error: Plugin could not be registered at 'html-webpack-plugin-after-emit'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/tapable/lib/Tapable.js:69:9)
    at Compilation.deprecated [as plugin] (internal/util.js:89:15)
    at /Users/zero/project/aixuexi/aixuexi-B-train/build/dev-server.js:67:14
    at SyncHook.eval [as call] (eval at create (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
    at SyncHook.lazyCompileHook (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Compiler.js:630:30)
    at /Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Compiler.compile (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Compiler.js:662:28)
    at /Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Watching._go (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Watching.js:41:32)
    at Watching._invalidate (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Watching.js:169:9)
    at /Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Watching.js:138:11
    at Watchpack.<anonymous> (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/node/NodeWatchFileSystem.js:59:4)
    at Object.onceWrapper (events.js:417:26)
    at Watchpack.emit (events.js:310:20)
    at Watchpack._onTimeout (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/watchpack/lib/watchpack.js:144:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by daxiazilong** [comment]
> ### **Environment**
> webpack@4.44.1
> html-webpack-plugin@4.3.0
> 
> ```
> Error: Plugin could not be registered at 'html-webpack-plugin-after-emit'. Hook was not found.
> BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'.
>     at Compilation.plugin (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/tapable/lib/Tapable.js:69:9)
>     at Compilation.deprecated [as plugin] (internal/util.js:89:15)
>     at /Users/zero/project/aixuexi/aixuexi-B-train/build/dev-server.js:67:14
>     at SyncHook.eval [as call] (eval at create (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
>     at SyncHook.lazyCompileHook (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/tapable/lib/Hook.js:154:20)
>     at Compiler.newCompilation (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Compiler.js:630:30)
>     at /Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Compiler.js:667:29
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
>     at Compiler.compile (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Compiler.js:662:28)
>     at /Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Watching.js:77:18
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
>     at Watching._go (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Watching.js:41:32)
>     at Watching._invalidate (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Watching.js:169:9)
>     at /Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/Watching.js:138:11
>     at Watchpack.<anonymous> (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/webpack/lib/node/NodeWatchFileSystem.js:59:4)
>     at Object.onceWrapper (events.js:417:26)
>     at Watchpack.emit (events.js:310:20)
>     at Watchpack._onTimeout (/Users/zero/project/aixuexi/aixuexi-B-train/node_modules/watchpack/lib/watchpack.js:144:7)
>     at listOnTimeout (internal/timers.js:549:17)
>     at processTimers (internal/timers.js:492:7)
> ```

兄弟，解决了吗
