### ISSUE TITLE
Call plugin('html').use(<Plugin>) first

### ISSUE THREAD

**Issue by Saint9** [jantimon/html-webpack-plugin#1565]
创建多页面配置
```
module.exports = {
  chainWebpack: config => {
    config
      .plugin('html')
      .tap(args => {
        args[0].title = 'mario'
        return args
      })
  },
  pages: {
    index: {
      entry: 'src/main.js',
      template: 'public/index.html',
      filename: 'index.html',
      title: 'Index Page',
      chunks: ['chunk-vendors', 'chunk-common', 'index']
    }
  }
}
```
上面是初始化项目添加一个`vue.config.js`，执行报错
```
Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('html').use(<Plugin>) first.
Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('html').use(<Plugin>) first.
    at Object.tap (/Users/aaron/Documents/Project/mult-vue/node_modules/webpack-chain/src/Plugin.js:26:15)
    at chainWebpack (/Users/aaron/Documents/Project/mult-vue/vue.config.js:6:8)
    at /Users/aaron/Documents/Project/mult-vue/node_modules/@vue/cli-service/lib/Service.js:236:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/aaron/Documents/Project/mult-vue/node_modules/@vue/cli-service/lib/Service.js:236:26)
    at Service.resolveWebpackConfig (/Users/aaron/Documents/Project/mult-vue/node_modules/@vue/cli-service/lib/Service.js:240:48)
    at PluginAPI.resolveWebpackConfig (/Users/aaron/Documents/Project/mult-vue/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/Users/aaron/Documents/Project/mult-vue/node_modules/@vue/cli-service/lib/commands/serve.js:75:31)
    at Service.run (/Users/aaron/Documents/Project/mult-vue/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at Object.<anonymous> (/Users/aaron/Documents/Project/mult-vue/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

chainWebpack配置是为使用CDN服务（现是为演示问题，简单写）
``` html
   <!-- require cdn assets js -->
    <% for (var i in htmlWebpackPlugin.options.cdn && htmlWebpackPlugin.options.cdn.js) { %>
    <script type="text/javascript" src="<%= htmlWebpackPlugin.options.cdn.js[i] %>"></script>
    <% } %>
```
```
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-standard": "^5.1.2",
```
求助，这个问题该如何解决

**Comment by gary-dgc** [comment]
see you [.use(HtmlWebpackPlugin)], guess you get error: 
`[ Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('html').use(<Plugin>) first.]. `
if you configured multi-pages in vue.config.js, the [plugin('html')] not exist in config, coz it's replaced with the multi-pages settings, to identify the correct html plugin name, you need to run command to list all the plugins:
```
npx vue-cli-service inspect --plugins
[
  'vue-loader',
  'define',
  'case-sensitive-paths',
  'friendly-errors',
  'html-index',
  'html-demo',
  'preload-index',
  'prefetch-index',
  'preload-oeditor',
  'prefetch-oeditor',
  'copy',
  'ThemeColorReplacer',
  'IgnorePlugin'
]

```
Now you can use following to modify the plugin options
```
      config.plugin('html-index')
        .tap(args => {
          args[0].cdn = assetsCDN
          return args
        })
      config.plugin('html-demo')
        .tap(args => {
          args[0].cdn = assetsCDN
          return args
        })
```
