### ISSUE TITLE
Upgrade from version 3 to 5 is breaking all my tests 

### ISSUE THREAD

**Issue by simkessy** [jantimon/html-webpack-plugin#1733]
## Current behaviour 💣
I've upgraded from version 3 to 5 and it's breaking all my tests 

![image](https://user-images.githubusercontent.com/5871660/154449645-d6f73649-a65a-4ce6-afc6-9eac6b62b799.png)

![image](https://user-images.githubusercontent.com/5871660/154449807-df15a7f5-8f2a-419c-97c3-14f88ee529e2.png)
```
 TypeError: Cannot read property 'Tag' of undefined

      at Object.<anonymous> (../../../node_modules/domhandler/lib/node.js:32:35)
      at Object.<anonymous> (../../../node_modules/domhandler/lib/index.js:15:14)
      at Object.<anonymous> (../../../node_modules/htmlparser2/lib/index.js:2:18)
      at Object.<anonymous> (../../../node_modules/cheerio/lib/parse.js:4:18)
      at Object.<anonymous> (../../../node_modules/cheerio/lib/cheerio.js:5:13)
      at Object.<anonymous> (../../../node_modules/cheerio/index.js:5:28)
      at Object.<anonymous> (../../../node_modules/enzyme/src/Utils.js:9:1)
      at Object.<anonymous> (../../../node_modules/enzyme/src/ShallowWrapper.js:5:1)
      at Object.<anonymous> (../../../node_modules/enzyme-to-json/utils.js:12:46)
      at Object.<anonymous> (../../../node_modules/enzyme-to-json/createSerializer.js:8:14)
      at Object.<anonymous> (../../../node_modules/enzyme-to-json/serializer.js:3:48)
          at Array.forEach (<anonymous>)
```
## Expected behaviour ☀️

I haven't changed anything in my tests, I need this library for webpack to build my html pages but updating this library ends up breaking all my tests. Expected behaviour would be for it not to break everything 

## Environment 🖥

Node.js v14.17.1
linux 5.4.0-1041-aws
6.14.13
@services/myApp@3.27.0 /home/ksimilien/code/pinboard/services/pq3/client
└── (empty)

(.venv) ~/code/pinboard/services/pq3/client$ npm ls html-webpack-plugin
@services/myApp@3.27.0 /home/ksimilien/code/pinboard/services/pq3/client
└── (empty)

    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "enzyme-to-json": "^3.4.4",

**Comment by simkessy** [comment]
@jantimon what packages or how do I fix it, I don't see how those breaking changes in this package interact with my Jest / Enzyme tests.

**Comment by jantimon** [comment]
hard to say - depends on:
 - node version
 - webpack version
 - webpack config 
 - other webpack plugins

**Comment by simkessy** [comment]
@jantimon

Node.js v14.17.1
"webpack": "^5.69.0",
I don't use webpack config for running tests so I don't think it's relevant 

Seems like others have had this issue https://stackoverflow.com/questions/68303360/cannot-read-property-tag-of-undefined-from-domhandler-in-react-js-app

**Comment by jantimon** [comment]
sorry i have never had this problem before and would need to debug it by myself
