### ISSUE TITLE
Error The loader didn't return html

### ISSUE THREAD

**Issue by zymapp** [jantimon/html-webpack-plugin#602]
webpack version: 2.2.1
html-webpack-plugin version: 2.28.0
config code
```
new ExtractTextPlugin('[name].css'),
    new HtmlWebpackPlugin({
        filename: './index.html',
        template: commonPath.indexHtml,
        showErrors: true,
    }),
```

error
* Html Webpack Plugin:
* Error: The loader "F:\Web\VueFrame\node_modules\html-webpack-
plugin\lib\loader.js!F:\Web\VueFrame\src\index.html" didn't return html.

### How is this going on?

**Comment by jantimon** [comment]
What's your loader configuration?

**Comment by zymapp** [comment]
loader config
```
 module: {
        rules: [{
            loader: 'vue-loader',
            include: commonPath.src,
            exclude: /node_modules/
        },{
            test: /\.js$/,
            loader: 'babel-loader',
            include: commonPath.src,
            exclude: /node_modules/
        },{
            test: /\.html$/,
            loader: 'html-loader'
        },{
            test: /\.(png|jpe?g|gif|svg)$/,
            loader: 'url-loader',
            options: {
                limit: 10240, 
                name: 'img/[name]-[hash:6].[ext]'
            }
        },{
            test: /\.(woff2?|eot|ttf|otf)$/,
            loader: 'url-loader',
            options:{
                limit: 10240, 
                name: 'fonts/[name]-[hash:6].[ext]'
            }
        },{
            test: /\.css$/,
            use: [
                'style-loader',
                'css-loader'
            ]
        }, {
            test: /\.less$/,
            use: [
                'style-loader',
                'css-loader',
                'less-loader'
            ]
        }, {
            test: /\.scss$/,
            use: [
                'style-loader',
                'css-loader',
                'sass-loader'
            ]
        }],
    }
```

**Comment by jantimon** [comment]
Hmm looks good

are 
`filename: './index.html',` and `template: commonPath.indexHtml,` the same?

**Comment by zymapp** [comment]
```
var rootPath = path.resolve(__dirname, '..');
var commonPath = {
    //build 后输出目录
    dist: path.join(rootPath, 'dist'),
    //入口html文件
    indexHtml: path.join(src, 'index.html'),
    //无需webpack处理的 静态资源目录
    staticDir: path.join(rootPath, 'static')
};
```

indexHtml value :
F:\Web\VueFrame\src\index.html

**Comment by jantimon** [comment]
https://github.com/jantimon/html-webpack-plugin/blob/master/index.js#L240
You could try to add some console log statements here to understand why it is not returning a propper template function:
https://github.com/jantimon/html-webpack-plugin/blob/master/lib/loader.js

**Comment by zymapp** [comment]
Is there a relationship with these warnings?
```
Warning: a promise was rejected with a non-error: [object String]
    at HtmlWebpackPlugin.evaluateCompilationResult (F:\Web\VueFrame\node_modules\html-webpack-plugin\index.js:242:15)
    at F:\Web\VueFrame\node_modules\html-webpack-plugin\index.js:117:21
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Compiler.<anonymous> (F:\Web\VueFrame\node_modules\html-webpack-plugin\index.js:110:8)
    at Compiler.applyPluginsAsyncSeries (F:\Web\VueFrame\node_modules\webpack\node_modules\tapable\lib\Tapable.js:142:13)
    at Compiler.emitAssets (F:\Web\VueFrame\node_modules\webpack\lib\Compiler.js:292:7)
    at onCompiled (F:\Web\VueFrame\node_modules\webpack\lib\Compiler.js:53:18)
    at F:\Web\VueFrame\node_modules\webpack\lib\Compiler.js:480:13
    at next (F:\Web\VueFrame\node_modules\webpack\node_modules\tapable\lib\Tapable.js:138:11)
    at Compiler.<anonymous> (F:\Web\VueFrame\node_modules\webpack\lib\CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (F:\Web\VueFrame\node_modules\webpack\node_modules\tapable\lib\Tapable.js:142:13)
    at F:\Web\VueFrame\node_modules\webpack\lib\Compiler.js:477:10
    at Compilation.applyPluginsAsyncSeries (F:\Web\VueFrame\node_modules\webpack\node_modules\tapable\lib\Tapable.js:131:46)
    at F:\Web\VueFrame\node_modules\webpack\lib\Compilation.js:640:19
    at Compilation.applyPluginsAsyncSeries (F:\Web\VueFrame\node_modules\webpack\node_modules\tapable\lib\Tapable.js:131:46)
    at F:\Web\VueFrame\node_modules\webpack\lib\Compilation.js:631:11
    at Compilation.applyPluginsAsyncSeries (F:\Web\VueFrame\node_modules\webpack\node_modules\tapable\lib\Tapable.js:131:46)
    at F:\Web\VueFrame\node_modules\webpack\lib\Compilation.js:626:10
    at next (F:\Web\VueFrame\node_modules\webpack\node_modules\tapable\lib\Tapable.js:138:11)
    at ExtractTextPlugin.<anonymous> (F:\Web\VueFrame\node_modules\extract-text-webpack-plugin\index.js:329:4)
    at Compilation.applyPluginsAsyncSeries (F:\Web\VueFrame\node_modules\webpack\node_modules\tapable\lib\Tapable.js:142:13)
    at sealPart2 (F:\Web\VueFrame\node_modules\webpack\lib\Compilation.js:622:9)

```

**Comment by jantimon** [comment]
Probably yes

**Comment by kevinthorley** [comment]
I ran into the same issue today. I started off with a different error, saying that "React is not defined". I got around this by adding a block to my webpack config:

`new webpack.ProvidePlugin({
    React: "react",
}),`

Here is the error I have now. There are not other error message along with this one:

Error: The loader "client/node_modules/html-webpack-plugin/lib/loader.js!client/src/index.template.ejs" didn't retu  rn html.

My html template (index.template.ejs) is as follows:

`<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <title>My App</title>
  </head>
  <body>
    <div id='app'></div>
  </body>
</html>`

**Comment by zymapp** [comment]
my problem solved,because my loader  configuration is missing content.
the original configuration:
```
 rules: [{
            loader: 'vue-loader',
            include: commonPath.src,
            exclude: /node_modules/
        },{
......
```
modified configuration
```
 rules: [{
            test: /\.vue$/,
            loader: 'vue-loader',
            include: commonPath.src,
            exclude: /node_modules/
        },{
......
```
add ```  test: /\.vue$/, ```
you look at your configuration
@kevinthorley

**Comment by jantimon** [comment]
Cool :)
