### ISSUE TITLE
Final loader didn't return a Buffer or String

### ISSUE THREAD

**Issue by alimazrooei** [jantimon/html-webpack-plugin#833]
this is the whole error text
```

ERROR in ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.pug
    Module build failed: Error: Final loader didn't return a Buffer or String
        at runLoaders (/home/mrmzr/Desktop/pugg/node_modules/webpack/lib/NormalModule.js:204:46)
        at /home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:370:3
        at iterateNormalLoaders (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
        at iterateNormalLoaders (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
        at /home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:233:3
        at runSyncOrAsync (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:124:12)
        at iterateNormalLoaders (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
        at iterateNormalLoaders (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
        at /home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:233:3
        at runSyncOrAsync (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:124:12)
        at iterateNormalLoaders (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
        at iterateNormalLoaders (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
        at /home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:233:3
        at runSyncOrAsync (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
        at iterateNormalLoaders (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
        at Array.<anonymous> (/home/mrmzr/Desktop/pugg/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
        at Storage.finished (/home/mrmzr/Desktop/pugg/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
        at /home/mrmzr/Desktop/pugg/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
        at /home/mrmzr/Desktop/pugg/node_modules/graceful-fs/graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)


```
and this is my webpack config
```
var HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
  entry:'./src/app.js',
    output:{
      path:'/home/mrmzr/Desktop/pugg/dist',
        filename:'b.js'
    },
  module:{
      loaders:[
        {
      test: /\.pug/,
      loaders: ['html-webpack-plugin', 'pug-html-loader'],
        }
]
  },
    plugins: [
    new HtmlWebpackPlugin({  // Also generate a test.html
      template: './src/index.pug'
    })
  ]
    
};
```
Please help me to solve this .
thank you .

**Comment by chet-manley** [comment]
Remove `html-webpack-plugin` from your `loaders`.

**Comment by alimazrooei** [comment]
thank you guys
it's done 
thank you
