### ISSUE TITLE
Using EJS with html-webpack-plugin

### ISSUE THREAD

**Issue by EddyVinck** [jantimon/html-webpack-plugin#955]
## Description

I try to use ```<%= htmlWebpackPlugin.files.chunks.main.entry %>``` so I can decide where my script is placed in my file. I need this because I want to include it before I include the Google Sheets JavaScript file. This compiles with ```.html``` files but not with ```.ejs``` files for some reason.

I'm currently looking for a templating engine to use for both my Webpack front-end workflow and on my NodeJS/Express app on the back-end. I chose EJS because it looked nice and it seems it's fairly common for back-end usage, however I am open to other templating engine suggestions if those work better with HTMLWebpackPlugin.

_This may be offtopic but I cannot get the EJS includes to work either with ejs-loader, so if someone can help with that then that would be great :)_

### Error Message & Stack Trace

```
URIError: Failed to decode param '/%3C%=%20htmlWebpackPlugin.files.chunks.main.entry%20%%3E'
    at decodeURIComponent (<anonymous>)
    at decode_param (C:\www-activityrandomizer-com\node_modules\express\lib\router\layer.js:172:12)
    at Layer.match (C:\www-activityrandomizer-com\node_modules\express\lib\router\layer.js:123:27)
    at matchLayer (C:\www-activityrandomizer-com\node_modules\express\lib\router\index.js:574:18)
    at next (C:\www-activityrandomizer-com\node_modules\express\lib\router\index.js:220:15)
    at expressInit (C:\www-activityrandomizer-com\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (C:\www-activityrandomizer-com\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\www-activityrandomizer-com\node_modules\express\lib\router\index.js:317:13)
    at C:\www-activityrandomizer-com\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\www-activityrandomizer-com\node_modules\express\lib\router\index.js:335:12)
    at next (C:\www-activityrandomizer-com\node_modules\express\lib\router\index.js:275:10)
    at query (C:\www-activityrandomizer-com\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (C:\www-activityrandomizer-com\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\www-activityrandomizer-com\node_modules\express\lib\router\index.js:317:13)
    at C:\www-activityrandomizer-com\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\www-activityrandomizer-com\node_modules\express\lib\router\index.js:335:12)
```

### Config

```js
module.exports = {
  entry: './src/index',
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      ...
        {
		test: /\.ejs$/,
		loader: 'ejs-loader',
		exclude: /node-modules/,
		query: {
			interpolate : /\{\{(.+?)\}\}/g,
			evaluate    : /\[\[(.+?)\]\]/g
		}
	}
      ...
    ]
  }
  plugins: [
    new HtmlWebpackPlugin({
	filename: 'index.html',				
	template: 'src/assets/html/index.ejs',
	hash: true,
	inject: false
    }),
    ...
  ]
}
```

Copy your template file:

```html
<head>
  <link rel="stylesheet" href="<%=htmlWebpackPlugin.files.chunks.main.css %>">
</head>
```

## Environment

```
Node.js v9.9.0
win32 10.0.16299
npm --version 5.6.0
webpack ^4.8.3
```

**Comment by jantimon** [comment]
Hey @EddyVinck 

we are using ejs by default for this plugin so you might try to remove the loader and it should just work.

Your stacktrace looks unrelated to this plugin - I am not sure how I could help you here.

**Comment by EddyVinck** [comment]
I will give that a try later and let you know if it worked, thanks!

**Comment by jantimon** [comment]
Cool 👍
