### ISSUE TITLE
TypeError: Converting circular structure to JSON. Webpack 4

### ISSUE THREAD

**Issue by BiosBoy** [jantimon/html-webpack-plugin#991]
## Expected behaviour
Work without any errors on dev or prod builds with webpack

## Current behaviour
So I just updated from webpack 3 to 4 version and now I always catch an error on my dev and prod builds. I cannot understnd why. I saw this issue https://github.com/jantimon/html-webpack-plugin/issues/870 but the solution - "chunksSortMode option and set it to "none" is does not assept my webpack config and throw a new error... And `npm i html-webpack-plugin@next` also does not help...

I currently stuck. So, this is the stack trace of my error. The webpackConfig I posted below. 

Thank you for any help!

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at visit (eact-apps/node_modules/toposort/index.js:29:50)
    at visit (eact-apps/node_modules/toposort/index.js:47:9)
    at visit (eact-apps/node_modules/toposort/index.js:47:9)
    at Function.toposort [as array] (eact-apps/node_modules/toposort/index.js:22:22)
    at Object.module.exports.dependency (eact-apps/node_modules/html-webpack-plugin/lib/chunksorter.js:50:35)
    at HtmlWebpackPlugin.sortChunks (eact-apps/node_modules/html-webpack-plugin/index.js:364:35)
    at eact-apps/node_modules/html-webpack-plugin/index.js:113:21
    at AsyncSeriesHook.eval [as callAsync] (eval at create (eact-apps/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (eact-apps/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.emitAssets (eact-apps/node_modules/webpack/lib/Compiler.js:311:19)
    at onCompiled (eact-apps/node_modules/webpack/lib/Watching.js:50:19)
    at hooks.afterCompile.callAsync.err (eact-apps/node_modules/webpack/lib/Compiler.js:500:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (eact-apps/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (eact-apps/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (eact-apps/node_modules/webpack/lib/Compiler.js:497:30)
```

## Environment

Windows 10,
NodeJs 6.0.1
Yarn 1.7.0
Webpack 4.12.1
html-webpack-plugin": "^3.2.0"

### Config

Copy the minimal `webpack.config.js` to produce this issue:
```
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
const debug = require('debug')('app:webpack:config')

// ------------------------------------
// Rules
// ------------------------------------
const rules = []

// JavaScript / JSON
rules.push(
  {
    test: /\.(js|jsx)$/,
    exclude: /node_modules/,
    loader: 'babel-loader',
    query: {
      cacheDirectory: true,
      plugins: [
        'babel-plugin-transform-class-properties',
        'babel-plugin-syntax-dynamic-import',
        [
          'babel-plugin-transform-runtime',
          {
            helpers: true,
            polyfill: true,
            regenerator: true
          }
        ],
        [
          'babel-plugin-transform-object-rest-spread',
          {
            useBuiltIns: false
          }
        ]
      ],
      presets: [
        'babel-preset-react',
        [
          'babel-preset-env',
          {
            modules: false,
            targets: {
              ie9: true
            },
            uglify: true
          }
        ]
      ]
    }
  },
  {
    type: 'javascript/auto',
    test: /\.json$/,
    loader: 'json-loader'
  }
)

// ------------------------------------
// Style Loaders
// ------------------------------------

rules.push(
  {
    test: /\.(s?)css$/,
    use: [MiniCssExtractPlugin.loader, 'css-loader', { loader: 'postcss-loader' }, 'sass-loader']
  },
  {
    test: /\.cssmodule$/,
    use: [
      MiniCssExtractPlugin.loader,
      'css-loader?modules&importLoaders=1&localIdentName=[local]___[hash:base64:5]',
      { loader: 'postcss-loader' },
      'sass-loader'
    ]
  }
)

// File loaders
/* eslint-disable */
rules.push(
  {
    test: /\.woff(\?.*)?$/,
    loader: 'url-loader?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/font-woff'
  },
  {
    test: /\.woff2(\?.*)?$/,
    loader: 'url-loader?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/font-woff2'
  },
  {
    test: /\.otf(\?.*)?$/,
    loader: 'file-loader?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=font/opentype'
  },
  {
    test: /\.ttf(\?.*)?$/,
    loader: 'url-loader?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/octet-stream'
  },
  {
    test: /\.eot(\?.*)?$/,
    loader: 'file-loader?prefix=fonts/&name=[path][name].[ext]'
  },
  {
    test: /\.svg(\?.*)?$/,
    loader: 'url-loader?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=image/svg+xml'
  },
  { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192' }
)

const createConfig = options => {
  const paths = options.utils_paths
  const __DEV__ = options.globals.__DEV__
  const __PROD__ = options.globals.__PROD__
  // TODO: sourceMap is not read from postcss.config.js because of a bug
  // remove it once postcss-loader is updated

  debug('Creating configuration.')
  const webpackConfig = {
    mode: __DEV__ ? 'development' : 'production',
    entry: paths.client('main.js'),
    name: 'client',
    target: 'web',
    devtool: options.compiler_devtool,
    optimization: {
      minimizer: [
        new UglifyJsPlugin({
          uglifyOptions: {
            compress: {
              unused: true,
              dead_code: true,
              warnings: false
            }
          },
          sourceMap: true
        })
      ],
      splitChunks: {
        chunks: 'all'
      }
    },
    performance: {
      hints: false
    },
    resolve: {
      modules: [paths.client(), 'node_modules'],
      extensions: ['.js', '.jsx', '.json']
    },
    module: {}
  }

  // ------------------------------------
  // Entry Points
  // ------------------------------------
  const APP_ENTRY = paths.client('main.js')

  webpackConfig.entry = {
    app: __DEV__
      ? [APP_ENTRY].concat(`webpack-hot-middleware/client?path=${options.compiler_public_path}__webpack_hmr`)
      : [APP_ENTRY]
  }

  // ------------------------------------
  // Bundle externals
  // ------------------------------------
  webpackConfig.externals = {
    react: 'React',
    'react-dom': 'ReactDOM'
  }

  // ------------------------------------
  // Bundle Output
  // ------------------------------------
  webpackConfig.output = {
    filename: '[name].[hash].js',
    path: paths.dist(),
    publicPath: options.compiler_public_path
  }

  // ------------------------------------
  // Plugins
  // ------------------------------------
  webpackConfig.plugins = [
    new webpack.DefinePlugin(options.globals),
    new MiniCssExtractPlugin({
      filename: '[name].[hash].css',
      chunkFilename: '[name].[hash].css'
    })
  ]

  if (__DEV__) {
    debug('Enable plugins for live development (HMR, NoErrors).')
    webpackConfig.plugins.push(
      new HtmlWebpackPlugin({
        template: paths.client('index.html'),
        filename: 'index.html',
        inject: 'body',
        minify: {
          collapseWhitespace: true
        },
        chunksSortMode: 'auto'
      }),
      new webpack.HotModuleReplacementPlugin(),
      new webpack.NoEmitOnErrorsPlugin()
    )
  } else if (__PROD__) {
    debug('Enable plugins for production')
    webpackConfig.plugins.push(
      new HtmlWebpackPlugin({
        template: paths.client(options.template),
        filename: options.template,
        minify: false,
        inject: false,
        chunksSortMode: 'auto'
      })
    )

    webpackConfig.plugins.push(
      new webpack.ProvidePlugin({
        fetch: 'exports-loader?self.fetch!whatwg-fetch'
      })
    )
  }

  webpackConfig.module.rules = rules

  return webpackConfig
}

module.exports.rules = rules

module.exports = createConfig

module.exports = {
  entry: 'app.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  module: {
    rules: [
      ...
    ]
  }
  plugins: [
    new HtmlWebpackPlugin(),
    ...
  ]
}
```

**Comment by sghoweri** [comment]
Same here - just ran into this exact same problem when working on a new Webpack Loader (A Twig template loader - but with native PHP under the hood!)

Changing my code so that I'm only passing this new loader `context.htmlWebpackPlugin` (or rather, filtering out all the Webpack data except for what htmlWebpackPlugin exposes) does seem to work for now however I'm worried this will have a bunch of sideeffects...

A better workaround for this would be amazing!

**Comment by jantimon** [comment]
The alpha version has a fix included.  
Is there any reason why you can't use it?

**Comment by BiosBoy** [comment]
@jantimon hi!

I tried to use the `npm i html-webpack-plugin@next` and for now it's work. But I worry about some side effects that we can grab from this alpha version. Is there some date for stable version of htmlWebpackPlugin 4.0.0?

Thank you.

**Comment by BiosBoy** [comment]
@jantimon and Yep. This is what I talking above - for now webpack compile my project without embed links in html template, like:
```
<link href="[object Object]" rel="stylesheet" />
<link href="[object Object]" rel="stylesheet" />
<script type="text/javascript" src="[object Object]"></script>
<script type="text/javascript" src="[object Object]"></script>
```

**Comment by jantimon** [comment]
@BiosBoy that's because of a breaking change. We had to switch to a new api structure:

https://github.com/jantimon/html-webpack-plugin/blob/bbc07a3a214e3b693e6c9e3d6404e146a0fc023a/index.js#L405-L418

try to add `.path` to your asset object.

**Comment by BiosBoy** [comment]
@jantimon yes, It's work, but in my case I fall into the another error after prod build
```
Uncaught TypeError: n.Component is not a constructor
    at Object.<anonymous> (index.js:22)
    at i (bootstrap:78)
    at Module.<anonymous> (Actions.js:22)
    at i (bootstrap:78)
    at Object.<anonymous> (main.js:3)
    at i (bootstrap:78)
    at Object.<anonymous> (main.js:27)
    at i (bootstrap:78)
    at a (bootstrap:45)
```

Is there is some date where we can expect on pdocution build of html-webpack-plugin v.4? 

Thanks

**Comment by jantimon** [comment]
It's hard to tell because it is blocked by webpack issues right now.  
Your TypeError is probably unrelated to the html-webpack-plugin.

**Comment by BiosBoy** [comment]
@jantimon you are right. The last problem is not goes from `html-webpack-plugin`. Solved! )

We all will be waiting from prod v.4 of html-webpack-plugin

**Comment by BiosBoy** [comment]
@jantimon solved by `html-webpack-plugin@next` and extra adding the `.path`. 

Your are right the last problem is not goes from html-webpack-plugin.

Cheers!

**Comment by jantimon** [comment]
Cool :)
